#include <furi.h>

/* generated by fbt from .png files in images folder */
#include <roulette_icons.h>

int32_t roulette_app(void* p) {
    UNUSED(p);
    FURI_LOG_I("TEST", "Hello world");
    FURI_LOG_I("TEST", "I'm roulette!");

    return 0;
}
